### ISSUE TITLE
how this works?

### ISSUE THREAD

**Issue by ramartinez7** [kpocza/1brc#1]
https://github.com/kpocza/1brc/blob/a85f9facf8743870171b5bff545cc6e9fe7aac67/1brc/Worker.cs#L91C5-L104C71

Hey Krisztián,

I'm curious about how this 'hacky version' for parsing the temperature value works. Could you please explain it further or direct me to the source where you found it?

**Comment by kpocza** [comment]
Please check this commit: https://github.com/kpocza/1brc/commit/ce77ce830e8866776132058629fbf149514fade6
I've commented the number parsing algorithm.
